apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::616390991061:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OZCNRGCI2R7A
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::616390991061:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-24T21:27:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "814"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7241ce64-5262-4f06-a39d-e3e0a9afbec8
